var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"id":102,"sl":12,"methods":[{"sl":24,"el":29,"sc":5},{"sl":31,"el":37,"sc":5},{"sl":39,"el":42,"sc":5},{"sl":44,"el":47,"sc":5},{"sl":49,"el":52,"sc":5},{"sl":54,"el":57,"sc":5},{"sl":59,"el":62,"sc":5},{"sl":64,"el":67,"sc":5},{"sl":69,"el":72,"sc":5},{"sl":74,"el":78,"sc":5}],"el":79,"name":"ConstructorArgsTest"},{"id":102,"sl":16,"methods":[{"sl":20,"el":21,"sc":9}],"el":22,"name":"ConstructorArgsTest.A"}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_49":{"methods":[{"sl":54}],"name":"testConstructorArgs_NullObject","statements":[{"sl":56}],"pass":true},"test_3":{"methods":[{"sl":59}],"name":"testConstructorArgs_WrongPrimitive","statements":[{"sl":61}],"pass":true},"test_47":{"methods":[{"sl":64}],"name":"testConstructorArgs_WrongNumberOfArgs","statements":[{"sl":66}],"pass":true},"test_65":{"methods":[{"sl":24},{"sl":31}],"name":"testConstructorArgs","statements":[{"sl":26},{"sl":28},{"sl":32},{"sl":33},{"sl":34},{"sl":36}],"pass":true},"test_38":{"methods":[{"sl":39}],"name":"testConstructorArgs_WrongArgument","statements":[{"sl":41}],"pass":true},"test_45":{"methods":[{"sl":49}],"name":"testConstructorArgs_PrimitiveForObject","statements":[{"sl":51}],"pass":true},"test_91":{"methods":[{"sl":44}],"name":"testConstructorArgs_NullPrimitive","statements":[{"sl":46}],"pass":true},"test_6":{"methods":[{"sl":20},{"sl":69}],"name":"testConstructorArgs_TypeExistsButPrivate","statements":[{"sl":71}],"pass":true},"test_69":{"methods":[{"sl":74}],"name":"testConstructorArgs_TypeExistsButNotStatic","statements":[{"sl":76}],"pass":true}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [6], [], [], [], [65], [], [65], [], [65], [], [], [65], [65], [65], [65], [], [65], [], [], [38], [], [38], [], [], [91], [], [91], [], [], [45], [], [45], [], [], [49], [], [49], [], [], [3], [], [3], [], [], [47], [], [47], [], [], [6], [], [6], [], [], [69], [], [69], [], [], []]
